<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#111827"><link rel="manifest" href="/manifest.json">
    <title>Oyalo Cloud | Internet access that runs itself</title>
    <script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body class="bg-slate-950 text-slate-100 antialiased">
<header class="border-b border-white/10 bg-slate-950/80 backdrop-blur sticky top-0 z-20"><nav class="max-w-7xl mx-auto px-5 h-18 py-3 flex items-center justify-between"><a href="/" class="flex items-center gap-3"><img class="w-10 h-10 rounded-xl" src="/images/logo-192.png" alt="Oyalo"><b class="tracking-wider">OYALO <span class="text-indigo-400">CLOUD</span></b></a><div class="flex items-center gap-3"><a href="#how-it-works" class="hidden sm:block text-sm text-slate-300 hover:text-white">How it works</a>@auth <a href="{{ auth()->user()->isSuperAdmin() ? route('superadmin.dashboard') : route('admin.dashboard') }}" class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-bold hover:bg-indigo-500">Open dashboard</a> @else <a href="{{ route('login') }}" class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-bold hover:bg-indigo-500">Sign in</a> @endauth</div></nav></header>
<main>
<section class="relative overflow-hidden"><div class="absolute inset-0 bg-[radial-gradient(circle_at_70%_30%,rgba(79,70,229,.25),transparent_30%),radial-gradient(circle_at_20%_70%,rgba(14,165,233,.16),transparent_28%)]"></div><div class="relative max-w-7xl mx-auto px-5 pt-20 pb-24 lg:pt-28 lg:pb-32 text-center"><p class="inline-flex gap-2 items-center rounded-full border border-indigo-400/30 bg-indigo-400/10 px-4 py-2 text-xs font-bold text-indigo-200"><i class="fa-solid fa-wifi"></i> HOTSPOT MANAGEMENT, SIMPLIFIED</p><h1 class="mt-7 text-4xl font-black tracking-tight sm:text-6xl max-w-4xl mx-auto">Internet access that <span class="text-transparent bg-clip-text bg-gradient-to-r from-indigo-300 to-cyan-300">runs itself.</span></h1><p class="mt-6 text-lg text-slate-300 max-w-2xl mx-auto">Sell Wi‑Fi packages, automate MikroTik access, manage smart devices, and keep every location in one clear workspace.</p><div class="mt-9 flex flex-wrap justify-center gap-3"><a href="{{ route('login') }}" class="rounded-xl bg-indigo-600 px-6 py-3 font-bold hover:bg-indigo-500">Manage your hotspot <i class="fa-solid fa-arrow-right ml-2"></i></a><a href="#how-it-works" class="rounded-xl border border-slate-600 px-6 py-3 font-bold hover:border-slate-400">See how it works</a></div><p class="mt-5 text-xs text-slate-500">Built for phones, tablets, desktops, and compatible smart TVs.</p></div></section>
<section id="how-it-works" class="max-w-7xl mx-auto px-5 py-16"><div class="text-center"><h2 class="text-3xl font-bold">Everything your hotspot needs</h2><p class="mt-3 text-slate-400">One platform for owners, operators, and guests.</p></div><div class="grid md:grid-cols-3 gap-5 mt-10"><article class="rounded-2xl border border-slate-800 bg-slate-900 p-7"><i class="fa-solid fa-credit-card text-2xl text-emerald-400"></i><h3 class="mt-5 text-xl font-bold">Sell & renew access</h3><p class="mt-2 text-sm leading-6 text-slate-400">Customers purchase a plan online. Operators can also create or renew subscriptions for someone in seconds.</p></article><article class="rounded-2xl border border-slate-800 bg-slate-900 p-7"><i class="fa-solid fa-router text-2xl text-indigo-400"></i><h3 class="mt-5 text-xl font-bold">Sync with MikroTik</h3><p class="mt-2 text-sm leading-6 text-slate-400">Queue customer and device changes to your router without opening public management ports.</p></article><article class="rounded-2xl border border-slate-800 bg-slate-900 p-7"><i class="fa-solid fa-tv text-2xl text-cyan-400"></i><h3 class="mt-5 text-xl font-bold">Install anywhere</h3><p class="mt-2 text-sm leading-6 text-slate-400">The guest portal is a progressive web app, designed for mobile and large-screen TV browsers alike.</p></article></div></section>
<section class="border-y border-slate-800 bg-slate-900/50"><div class="max-w-5xl mx-auto px-5 py-14 text-center"><h2 class="text-2xl font-bold">Ready to run a better hotspot?</h2><p class="mt-3 text-slate-400">Sign in to manage locations, packages, devices, and subscriptions.</p><a href="{{ route('login') }}" class="inline-block mt-6 rounded-xl bg-white text-slate-950 px-6 py-3 font-bold hover:bg-slate-200">Sign in to Oyalo Cloud</a></div></section>
</main><footer class="max-w-7xl mx-auto px-5 py-8 flex flex-col sm:flex-row gap-2 justify-between text-sm text-slate-500"><span>© {{ date('Y') }} Oyalo Cloud</span><span>Cloud hotspot management</span></footer>
<script src="/js/pwa.js"></script>
</body></html>
