@extends('layouts.app')
@section('title', 'System Logs')
@section('page_title', auth()->user()->isSuperAdmin() ? 'Platform Logs & Delivery Status' : 'Your Delivery & Activity Logs')
@section('role', auth()->user()->isSuperAdmin() ? 'Super Administrator — all activity' : 'Hotspot Business Owner')

@section('content')
@if(config('mail.default') === 'log')
<div class="mb-6 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-100"><i class="fa-solid fa-triangle-exclamation mr-2"></i><strong>Email is in log mode.</strong> Emails are recorded locally and are not delivered. Set <code class="rounded bg-slate-950/40 px-1">MAIL_MAILER=smtp</code> with valid SMTP credentials in the deployed <code class="rounded bg-slate-950/40 px-1">.env</code>, then run <code class="rounded bg-slate-950/40 px-1">php artisan config:clear</code>.</div>
@endif
<div class="space-y-8">
<section class="rounded-2xl border border-slate-800 bg-slate-900 p-5 sm:p-6 shadow-xl"><div class="mb-5 flex items-center justify-between"><div><h2 class="text-lg font-bold text-white"><i class="fa-solid fa-comment-sms mr-2 text-indigo-400"></i>SMS delivery log</h2><p class="mt-1 text-xs text-slate-400">Review sent and failed customer voucher messages.</p></div><span class="text-xs text-slate-500">Latest 100</span></div><div class="overflow-x-auto"><table class="w-full min-w-[700px] text-left text-sm"><thead><tr class="border-b border-slate-800 text-xs uppercase text-slate-400"><th class="pb-3">Time</th><th class="pb-3">Customer</th><th class="pb-3">Phone</th><th class="pb-3">Message</th><th class="pb-3">Status</th></tr></thead><tbody class="divide-y divide-slate-800/60">@forelse($smsLogs as $log)<tr><td class="py-3 text-xs text-slate-400">{{ $log->created_at->format('d M H:i') }}</td><td class="py-3 text-white">{{ $log->customer?->voucher_code ?? $log->customer?->username ?? '—' }}</td><td class="py-3 text-slate-300">{{ $log->phone_number }}</td><td class="max-w-sm py-3 text-xs text-slate-400 break-words">{{ $log->message }}@if($log->error_message)<br><span class="text-rose-300">{{ $log->error_message }}</span>@endif</td><td class="py-3"><span @class(['rounded-full px-2 py-1 text-xs','bg-emerald-500/10 text-emerald-300'=>$log->status==='sent','bg-rose-500/10 text-rose-300'=>$log->status==='failed'])>{{ ucfirst($log->status) }}</span></td></tr>@empty<tr><td colspan="5" class="py-10 text-center text-slate-500">No SMS logs yet.</td></tr>@endforelse</tbody></table></div></section>
<section class="rounded-2xl border border-slate-800 bg-slate-900 p-5 sm:p-6 shadow-xl"><div class="mb-5 flex items-center justify-between"><div><h2 class="text-lg font-bold text-white"><i class="fa-solid fa-envelope-circle-check mr-2 text-cyan-400"></i>Owner email log</h2><p class="mt-1 text-xs text-slate-400">Email attempts for subscription notifications. Failed entries include the reason when available.</p></div><span class="text-xs text-slate-500">Latest 100</span></div><div class="overflow-x-auto"><table class="w-full min-w-[700px] text-left text-sm"><thead><tr class="border-b border-slate-800 text-xs uppercase text-slate-400"><th class="pb-3">Time</th><th class="pb-3">Location</th><th class="pb-3">To</th><th class="pb-3">Subject / error</th><th class="pb-3">Status</th></tr></thead><tbody class="divide-y divide-slate-800/60">@forelse($emailLogs as $log)<tr><td class="py-3 text-xs text-slate-400">{{ $log->created_at->format('d M H:i') }}</td><td class="py-3 text-white">{{ $log->location?->name ?? '—' }}</td><td class="py-3 text-slate-300">{{ $log->to }}</td><td class="max-w-sm py-3 text-xs text-slate-400 break-words">{{ $log->subject }}@if($log->error_message)<br><span class="text-rose-300">{{ $log->error_message }}</span>@endif</td><td class="py-3"><span @class(['rounded-full px-2 py-1 text-xs','bg-emerald-500/10 text-emerald-300'=>$log->status==='sent','bg-rose-500/10 text-rose-300'=>$log->status==='failed'])>{{ ucfirst($log->status) }}</span></td></tr>@empty<tr><td colspan="5" class="py-10 text-center text-slate-500">No owner email attempts yet. Enable subscription email alerts on the dashboard.</td></tr>@endforelse</tbody></table></div></section>
<section class="rounded-2xl border border-slate-800 bg-slate-900 p-5 sm:p-6 shadow-xl"><div class="mb-5"><h2 class="text-lg font-bold text-white"><i class="fa-solid fa-clock-rotate-left mr-2 text-violet-400"></i>Activity audit trail</h2><p class="mt-1 text-xs text-slate-400">@if(auth()->user()->isSuperAdmin()) Platform-wide administrative actions. @else Your administrative actions. @endif</p></div><div class="overflow-x-auto"><table class="w-full min-w-[650px] text-left text-sm"><thead><tr class="border-b border-slate-800 text-xs uppercase text-slate-400"><th class="pb-3">Time</th><th class="pb-3">Actor</th><th class="pb-3">Action</th><th class="pb-3">Description</th><th class="pb-3">IP</th></tr></thead><tbody class="divide-y divide-slate-800/60">@forelse($activityLogs as $log)<tr><td class="py-3 text-xs text-slate-400">{{ $log->created_at->format('d M H:i') }}</td><td class="py-3 text-white">{{ $log->user?->name ?? 'System / Router' }}</td><td class="py-3 font-mono text-xs text-indigo-300">{{ $log->action }}</td><td class="max-w-sm py-3 text-slate-300 break-words">{{ $log->description }}</td><td class="py-3 font-mono text-xs text-slate-500">{{ $log->ip_address ?? '—' }}</td></tr>@empty<tr><td colspan="5" class="py-10 text-center text-slate-500">No activity has been recorded yet.</td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection
